BDEPEND=>=sys-devel/binutils-x86_64-bunnix-2.30 sys-devel/gnuconfig >=app-portage/elt-patches-20240116 >=dev-vcs/git-1.8.2.1[curl] app-alternatives/yacc >=sys-devel/flex-2.5.4 nls? ( sys-devel/gettext ) test? ( || ( dev-lang/python:3.12 dev-lang/python:3.11 dev-lang/python:3.10 ) >=dev-util/dejagnu-1.4.4 >=sys-devel/autogen-5.5.4 )
DEFINED_PHASES=compile configure install postinst postrm preinst prepare pretend setup test unpack
DEPEND=sys-libs/zlib virtual/libiconv nls? ( virtual/libintl ) >=dev-libs/gmp-4.3.2:0= >=dev-libs/mpfr-2.4.2:0= >=dev-libs/mpc-0.8.1:0=
DESCRIPTION=The GNU Compiler Collection
EAPI=8
HOMEPAGE=https://gcc.gnu.org/
INHERIT=toolchain
IUSE=test vanilla +nls
LICENSE=GPL-3+ LGPL-3+ || ( GPL-3+ libgcc libstdc++ gcc-runtime-library-exception-3.1 ) FDL-1.3+
PDEPEND=>=sys-devel/gcc-config-2.11
PROPERTIES=live
RDEPEND=sys-libs/zlib virtual/libiconv nls? ( virtual/libintl ) >=dev-libs/gmp-4.3.2:0= >=dev-libs/mpfr-2.4.2:0= >=dev-libs/mpc-0.8.1:0=
RESTRICT=test !test? ( test )
SLOT=13
SRC_URI=test? ( https://gitweb.gentoo.org/proj/gcc-patches.git/plain/scripts/testsuite-management/validate_failures.py?id=a447cd6dee206facb66720bdacf0c765a8b09f33 -> gcc-validate-failures-a447cd6dee206facb66720bdacf0c765a8b09f33.py )
_eclasses_=edo	367e103a74bf77e6a8da7894d999fa3c	toolchain-funcs	333970c740aa7b1a92e4fcdc52f612bd	multilib	c19072c3cd7ac5cb21de013f7e9832e0	flag-o-matic	e503ea5acc20410237ba33ec3f7c857d	gnuconfig	a397adda6984a4c423e28ac274c1ba98	libtool	5f49a16f67f81bdf873e3d1f10b10001	pax-utils	91d47e5d20627c717aa878b9167c62a8	multiprocessing	30ead54fa2e2b5f9cd4e612ffc34d0fe	python-utils-r1	6881b056477c23167d9a6b33e146374e	python-any-r1	5af215c3da6aef17a2d5e02968df1d5a	prefix	eab3c99d77fe00506c109c8a736186f7	git-r3	875eb471682d3e1f18da124be97dcc81	toolchain	b44188ee6724a1480c6d7705791a973f
_md5_=767eef4bc82cb3d77e6bcaedee228006
